//////////////////////////////////////////////////////////////////////////
//
// DDS MESSAGE, OSS-MMI
//
// Created	: 2012.06.10    Lee-Jiwoong
// Updated	: 2012.06.21  : Lee-SooJung
//////////////////////////////////////////////////////////////////////////


//------------------------------------------------------------------------
//	OSS MMI -> CMS
//------------------------------------------------------------------------
//	1. DMSG_OSSMMI_SENSORSTATE			자함센서 상태정보
//	2. DMSG_OSSMMI_GPS					GPS Data
//	3. DMSG_OSSMMI_GYRO					GYRO Data
//	4. DMSG_OSSMMI_EMLOG				EM-log data
//	5. DMSG_OSSMMI_WIND					풍향풍속 Data
//	6. DMSG_OSSMMI_TEMP					기온기압 Data
//	7. DMSG_OSSMMI_ECHO					에코사운드 (잠수함 수심)
//  8. DMSG_OSSMMI_PLATFORM				플랫폼 정보응답
//------------------------------------------------------------------------


//	1. 자함센서 상태정보
struct DMSG_OSSMMI_SENSORSTATE
{
	char	gpsStatus;			// GPS 상태			(0 : 정상, 1 : 오류)
	char	gyroStatus;			// Gyro 상태		(0 : 정상, 1 : 오류)
	char	emLogStatus;		// EM-Log 상태		(0 : 정상, 1 : 오류)
	char	anemometerStatus;	// 풍향풍속 상태	(0 : 정상, 1 : 오류)
	char	airStatus;			// 기온기압 상태	(0 : 정상, 1 : 오류)
};


//	2. GPS Data
struct DMSG_OSSMMI_GPS
{
	double				latitude;		// 자함 위치(위도)
	double				longitude;		// 자함 위치(경도)
	unsigned short		year;			// 년
	char				month;			// 월
	char				day;			// 일
	unsigned long		sec;			// 초단위 현재시간
};


//	3. GYRO Data
struct DMSG_OSSMMI_GYRO
{
	double	heading;					// 자함 헤딩
	double	roll;						// 자함 롤
	double	pitch;						// 자함 피치
	long	rate_heading;			 
	long	rate_roll;				 
	long	rate_pitch;				
};


//	4. EM-log data
struct DMSG_OSSMMI_EMLOG
{
	double	velocity_north;
	double	velocity_east;
	double	velocity_down;
	double	accel_nort;	
	double	accel_east;
	double	accel_down;
};


//	5. 풍향풍속 Data
struct DMSG_OSSMMI_WIND
{
	float	wind_direction;				// 풍향(degree)
	float	wind_speed;					// 풍속(m/s)
};


//	6. 기온기압 Data
struct DMSG_OSSMMI_TEMP
{
	float	temp;						// 기온(degree)
	float	pressure;					// 기압(hPa/mb)
	float	humidity;					// 습도(%)
};


//	7. 에코사운드 (잠수함수심)
struct DMSG_OSSMMI_ECHO
{
	double	dWaterDepth;
	double	dDivingDepth;
};


// 8. 플랫폼 정보응답
struct DMSG_OSSMMI_PLATFORM
{
	char	byPlatform;
};


//------------------------------------------------------------------------
//	CMS -> OSS MMI
//------------------------------------------------------------------------
//	1. DMSG_OSSMMI_PLATFORMREQ			방위표적요청
//------------------------------------------------------------------------


//	1. 방위표적요청
struct DMSG_OSSMMI_PLATFORMREQ	
{
	char	byPlatformReq;
};