/*
-----------------------------------------------------------------------------
Filename:    Test1.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.8.x Application Wizard for VC10 (May 2012)
      https://bitbucket.org/jacmoe/ogreappwizards
-----------------------------------------------------------------------------
*/
#ifndef __Test1_h_
#define __Test1_h_

#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../res/resource.h"
#endif


class Test1 : public BaseApplication
{
public:
    Test1(void);
    virtual ~Test1(void);

protected:
    virtual void createScene(void);
    virtual void destroyScene(void);
    virtual bool frameStarted(const Ogre::FrameEvent& evt);
    virtual bool frameEnded(const Ogre::FrameEvent& evt);
    virtual bool frameRenderingQueued(const Ogre::FrameEvent& evt);
    virtual bool keyPressed(const OIS::KeyEvent &arg);
    virtual bool keyReleased(const OIS::KeyEvent &arg);

protected:

	bool	m_bRotateX;
	bool	m_bRotateY;
	bool	m_bRotateZ;

	Ogre::Real	m_rRotateX;
	Ogre::Real	m_rRotateY;
	Ogre::Real	m_rRotateZ;

	/// rotate angle is 10 degree
	static const int	ROTATE_ANGLE_PER_SEC	= 10;	
};

#endif // #ifndef __Test1_h_
