/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_w_main (void)
{
  GtkWidget *w_main;
  GtkWidget *vbox1;
  GtkWidget *menubar;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkAccelGroup *file_menu_accels;
  GtkWidget *preferences;
  GtkWidget *exit;
  GtkWidget *node;
  GtkWidget *node_menu;
  GtkAccelGroup *node_menu_accels;
  GtkWidget *node_list;
  GtkWidget *node_add;
  GtkWidget *node_rm;
  GtkWidget *hb;
  GtkWidget *hb_menu;
  GtkAccelGroup *hb_menu_accels;
  GtkWidget *hb_list;
  GtkWidget *hb_add;
  GtkWidget *hb_add_menu;
  GtkAccelGroup *hb_add_menu_accels;
  GtkWidget *hb_add_net;
  GtkWidget *hb_add_disk;
  GtkWidget *hb_rm;
  GtkWidget *services;
  GtkWidget *services_menu;
  GtkAccelGroup *services_menu_accels;
  GtkWidget *serv_list;
  GtkWidget *srv_add;
  GtkWidget *serv_rm;
  GtkWidget *help;
  GtkWidget *help_menu;
  GtkAccelGroup *help_menu_accels;
  GtkWidget *help_about;
  GtkWidget *vpaned1;
  GtkWidget *scrolledwindow2;
  GtkWidget *clist1;
  GtkWidget *l_service;
  GtkWidget *l_primary;
  GtkWidget *l_statusp;
  GtkWidget *l_secondary;
  GtkWidget *l_statuss;
  GtkWidget *vpaned2;
  GtkWidget *scrolledwindow3;
  GtkWidget *clist2;
  GtkWidget *l_node;
  GtkWidget *l_interface;
  GtkWidget *l_status;
  GtkWidget *l_data;
  GtkWidget *scrolledwindow1;
  GtkWidget *log_zone;

  w_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_main), "w_main", w_main);
  gtk_window_set_title (GTK_WINDOW (w_main), _("EZ-HA Gui"));
  gtk_window_set_default_size (GTK_WINDOW (w_main), 510, 300);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (w_main), vbox1);

  menubar = gtk_menu_bar_new ();
  gtk_widget_ref (menubar);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "menubar", menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar, FALSE, FALSE, 0);

  file = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (menubar), file);

  file_menu = gtk_menu_new ();
  gtk_widget_ref (file_menu);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "file_menu", file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);
  file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menu));

  preferences = gtk_menu_item_new_with_label (_("Preferences"));
  gtk_widget_ref (preferences);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "preferences", preferences,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preferences);
  gtk_container_add (GTK_CONTAINER (file_menu), preferences);

  exit = gtk_menu_item_new_with_label (_("Exit"));
  gtk_widget_ref (exit);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "exit", exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit);
  gtk_container_add (GTK_CONTAINER (file_menu), exit);

  node = gtk_menu_item_new_with_label (_("Node"));
  gtk_widget_ref (node);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "node", node,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (node);
  gtk_container_add (GTK_CONTAINER (menubar), node);

  node_menu = gtk_menu_new ();
  gtk_widget_ref (node_menu);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "node_menu", node_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (node), node_menu);
  node_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (node_menu));

  node_list = gtk_menu_item_new_with_label (_("List"));
  gtk_widget_ref (node_list);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "node_list", node_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (node_list);
  gtk_container_add (GTK_CONTAINER (node_menu), node_list);

  node_add = gtk_menu_item_new_with_label (_("Add"));
  gtk_widget_ref (node_add);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "node_add", node_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (node_add);
  gtk_container_add (GTK_CONTAINER (node_menu), node_add);

  node_rm = gtk_menu_item_new_with_label (_("Remove"));
  gtk_widget_ref (node_rm);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "node_rm", node_rm,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (node_rm);
  gtk_container_add (GTK_CONTAINER (node_menu), node_rm);

  hb = gtk_menu_item_new_with_label (_("Heartbeats"));
  gtk_widget_ref (hb);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "hb", hb,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hb);
  gtk_container_add (GTK_CONTAINER (menubar), hb);

  hb_menu = gtk_menu_new ();
  gtk_widget_ref (hb_menu);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "hb_menu", hb_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (hb), hb_menu);
  hb_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (hb_menu));

  hb_list = gtk_menu_item_new_with_label (_("List"));
  gtk_widget_ref (hb_list);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "hb_list", hb_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hb_list);
  gtk_container_add (GTK_CONTAINER (hb_menu), hb_list);

  hb_add = gtk_menu_item_new_with_label (_("Add"));
  gtk_widget_ref (hb_add);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "hb_add", hb_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hb_add);
  gtk_container_add (GTK_CONTAINER (hb_menu), hb_add);

  hb_add_menu = gtk_menu_new ();
  gtk_widget_ref (hb_add_menu);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "hb_add_menu", hb_add_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (hb_add), hb_add_menu);
  hb_add_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (hb_add_menu));

  hb_add_net = gtk_menu_item_new_with_label (_("Net"));
  gtk_widget_ref (hb_add_net);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "hb_add_net", hb_add_net,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hb_add_net);
  gtk_container_add (GTK_CONTAINER (hb_add_menu), hb_add_net);

  hb_add_disk = gtk_menu_item_new_with_label (_("Disk"));
  gtk_widget_ref (hb_add_disk);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "hb_add_disk", hb_add_disk,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hb_add_disk);
  gtk_container_add (GTK_CONTAINER (hb_add_menu), hb_add_disk);

  hb_rm = gtk_menu_item_new_with_label (_("Remove"));
  gtk_widget_ref (hb_rm);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "hb_rm", hb_rm,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hb_rm);
  gtk_container_add (GTK_CONTAINER (hb_menu), hb_rm);

  services = gtk_menu_item_new_with_label (_("Services"));
  gtk_widget_ref (services);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "services", services,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (services);
  gtk_container_add (GTK_CONTAINER (menubar), services);

  services_menu = gtk_menu_new ();
  gtk_widget_ref (services_menu);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "services_menu", services_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (services), services_menu);
  services_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (services_menu));

  serv_list = gtk_menu_item_new_with_label (_("List"));
  gtk_widget_ref (serv_list);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "serv_list", serv_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (serv_list);
  gtk_container_add (GTK_CONTAINER (services_menu), serv_list);

  srv_add = gtk_menu_item_new_with_label (_("Add"));
  gtk_widget_ref (srv_add);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "srv_add", srv_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (srv_add);
  gtk_container_add (GTK_CONTAINER (services_menu), srv_add);

  serv_rm = gtk_menu_item_new_with_label (_("Remove"));
  gtk_widget_ref (serv_rm);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "serv_rm", serv_rm,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (serv_rm);
  gtk_container_add (GTK_CONTAINER (services_menu), serv_rm);

  help = gtk_menu_item_new_with_label (_("Help"));
  gtk_widget_ref (help);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "help", help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help);
  gtk_container_add (GTK_CONTAINER (menubar), help);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help));

  help_menu = gtk_menu_new ();
  gtk_widget_ref (help_menu);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "help_menu", help_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help), help_menu);
  help_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help_menu));

  help_about = gtk_menu_item_new_with_label (_("About"));
  gtk_widget_ref (help_about);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "help_about", help_about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help_about);
  gtk_container_add (GTK_CONTAINER (help_menu), help_about);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), vpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (vpaned1), 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_paned_pack1 (GTK_PANED (vpaned1), scrolledwindow2, TRUE, FALSE);

  clist1 = gtk_clist_new (5);
  gtk_widget_ref (clist1);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "clist1", clist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), clist1);
  gtk_widget_set_usize (clist1, 540, 100);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 100);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 100);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 100);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 100);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 100);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  l_service = gtk_label_new (_("Service"));
  gtk_widget_ref (l_service);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "l_service", l_service,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_service);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, l_service);

  l_primary = gtk_label_new (_("Primary"));
  gtk_widget_ref (l_primary);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "l_primary", l_primary,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_primary);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, l_primary);

  l_statusp = gtk_label_new (_("Status Primary"));
  gtk_widget_ref (l_statusp);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "l_statusp", l_statusp,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_statusp);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, l_statusp);

  l_secondary = gtk_label_new (_("Secondary"));
  gtk_widget_ref (l_secondary);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "l_secondary", l_secondary,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_secondary);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, l_secondary);

  l_statuss = gtk_label_new (_("Status Secondary"));
  gtk_widget_ref (l_statuss);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "l_statuss", l_statuss,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_statuss);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, l_statuss);

  vpaned2 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned2);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "vpaned2", vpaned2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned2);
  gtk_paned_pack2 (GTK_PANED (vpaned1), vpaned2, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned2), 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_paned_pack1 (GTK_PANED (vpaned2), scrolledwindow3, TRUE, FALSE);

  clist2 = gtk_clist_new (4);
  gtk_widget_ref (clist2);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "clist2", clist2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), clist2);
  gtk_widget_set_usize (clist2, -2, 100);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 3, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist2));

  l_node = gtk_label_new (_("Node"));
  gtk_widget_ref (l_node);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "l_node", l_node,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_node);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 0, l_node);

  l_interface = gtk_label_new (_("Interface"));
  gtk_widget_ref (l_interface);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "l_interface", l_interface,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_interface);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 1, l_interface);

  l_status = gtk_label_new (_("Status"));
  gtk_widget_ref (l_status);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "l_status", l_status,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_status);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 2, l_status);

  l_data = gtk_label_new (_("Date"));
  gtk_widget_ref (l_data);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "l_data", l_data,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_data);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 3, l_data);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_paned_pack2 (GTK_PANED (vpaned2), scrolledwindow1, TRUE, FALSE);

  log_zone = gtk_text_new (NULL, NULL);
  gtk_widget_ref (log_zone);
  gtk_object_set_data_full (GTK_OBJECT (w_main), "log_zone", log_zone,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (log_zone);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), log_zone);
  gtk_widget_set_usize (log_zone, -2, 50);

  gtk_signal_connect (GTK_OBJECT (w_main), "destroy",
                      GTK_SIGNAL_FUNC (on_w_main_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (preferences), "activate",
                      GTK_SIGNAL_FUNC (on_preferences_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit), "activate",
                      GTK_SIGNAL_FUNC (on_exit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (node_list), "activate",
                      GTK_SIGNAL_FUNC (on_nodes_list_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (node_add), "activate",
                      GTK_SIGNAL_FUNC (on_node_add_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (node_rm), "activate",
                      GTK_SIGNAL_FUNC (on_node_rm_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hb_list), "activate",
                      GTK_SIGNAL_FUNC (on_hb_list_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hb_add), "activate",
                      GTK_SIGNAL_FUNC (on_hb_add_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hb_add_net), "activate",
                      GTK_SIGNAL_FUNC (on_hb_add_net_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hb_add_disk), "activate",
                      GTK_SIGNAL_FUNC (on_hb_add_disk_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (hb_rm), "activate",
                      GTK_SIGNAL_FUNC (on_hb_rm_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (serv_list), "activate",
                      GTK_SIGNAL_FUNC (on_srv_list_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (srv_add), "activate",
                      GTK_SIGNAL_FUNC (on_srv_add_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (serv_rm), "activate",
                      GTK_SIGNAL_FUNC (on_srv_rm_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (help_about), "activate",
                      GTK_SIGNAL_FUNC (on_help_about_activate),
                      NULL);

  return w_main;
}

GtkWidget*
create_w_preferences (void)
{
  GtkWidget *w_preferences;
  GtkWidget *vbox2;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *button2;

  w_preferences = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_preferences), "w_preferences", w_preferences);
  gtk_window_set_title (GTK_WINDOW (w_preferences), _("Preferences"));

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (w_preferences), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (w_preferences), vbox2);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (w_preferences), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("Refresh time:"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (w_preferences), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label1), 3, 0);

  spinbutton1_adj = gtk_adjustment_new (5, 1, 120, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_ref (spinbutton1);
  gtk_object_set_data_full (GTK_OBJECT (w_preferences), "spinbutton1", spinbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton1);
  gtk_box_pack_start (GTK_BOX (hbox1), spinbutton1, TRUE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (w_preferences), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox1, TRUE, TRUE, 0);

  button1 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (w_preferences), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_with_label (_("CANCEL"));
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (w_preferences), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_button1_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (on_button2_clicked),
                      NULL);

  return w_preferences;
}

GtkWidget*
create_w_nodes_list (void)
{
  GtkWidget *w_nodes_list;
  GtkWidget *vbox3;
  GtkWidget *scrolledwindow4;
  GtkWidget *clist_nodes;
  GtkWidget *l_nodes;
  GtkWidget *button3;

  w_nodes_list = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_nodes_list), "w_nodes_list", w_nodes_list);
  gtk_widget_set_usize (w_nodes_list, 180, -2);
  gtk_window_set_title (GTK_WINDOW (w_nodes_list), _("Nodes list"));

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_list), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (w_nodes_list), vbox3);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_list), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow4, TRUE, TRUE, 0);

  clist_nodes = gtk_clist_new (1);
  gtk_widget_ref (clist_nodes);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_list), "clist_nodes", clist_nodes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist_nodes);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), clist_nodes);
  gtk_clist_set_column_width (GTK_CLIST (clist_nodes), 0, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist_nodes));

  l_nodes = gtk_label_new (_("Nodes"));
  gtk_widget_ref (l_nodes);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_list), "l_nodes", l_nodes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (l_nodes);
  gtk_clist_set_column_widget (GTK_CLIST (clist_nodes), 0, l_nodes);

  button3 = gtk_button_new_with_label (_("Close"));
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_list), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (vbox3), button3, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_button3_clicked),
                      NULL);

  return w_nodes_list;
}

GtkWidget*
create_w_nodes_add (void)
{
  GtkWidget *w_nodes_add;
  GtkWidget *vbox4;
  GtkWidget *hbox2;
  GtkWidget *label3;
  GtkWidget *entry1;
  GtkWidget *hbuttonbox2;
  GtkWidget *button4;
  GtkWidget *button5;

  w_nodes_add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_nodes_add), "w_nodes_add", w_nodes_add);
  gtk_window_set_title (GTK_WINDOW (w_nodes_add), _("Add nodes"));

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_add), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (w_nodes_add), vbox4);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_add), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox2, TRUE, TRUE, 0);

  label3 = gtk_label_new (_("Node name:"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_add), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label3), 3, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_add), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox2), entry1, TRUE, TRUE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_add), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox2, TRUE, TRUE, 0);
  gtk_widget_set_usize (hbuttonbox2, 200, -2);

  button4 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_add), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  button5 = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_add), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button5);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_button4_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (on_button5_clicked),
                      NULL);

  return w_nodes_add;
}

GtkWidget*
create_w_nodes_rm (void)
{
  GtkWidget *w_nodes_rm;
  GtkWidget *vbox5;
  GtkWidget *hbox3;
  GtkWidget *label4;
  GtkWidget *combo1;
  GtkWidget *combo_entry1;
  GtkWidget *hbuttonbox3;
  GtkWidget *button6;
  GtkWidget *button7;

  w_nodes_rm = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_nodes_rm), "w_nodes_rm", w_nodes_rm);
  gtk_window_set_title (GTK_WINDOW (w_nodes_rm), _("Remove nodes"));

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_rm), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (w_nodes_rm), vbox5);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_rm), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox3, TRUE, TRUE, 0);

  label4 = gtk_label_new (_("Node to remove:"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_rm), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label4), 3, 0);

  combo1 = gtk_combo_new ();
  gtk_widget_ref (combo1);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_rm), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo1);
  gtk_box_pack_start (GTK_BOX (hbox3), combo1, TRUE, TRUE, 0);

  combo_entry1 = GTK_COMBO (combo1)->entry;
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_rm), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_rm), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox5), hbuttonbox3, TRUE, TRUE, 0);

  button6 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_rm), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);

  button7 = gtk_button_new_with_label (_("CANCEL"));
  gtk_widget_ref (button7);
  gtk_object_set_data_full (GTK_OBJECT (w_nodes_rm), "button7", button7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button7);
  GTK_WIDGET_SET_FLAGS (button7, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (on_button6_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button7), "clicked",
                      GTK_SIGNAL_FUNC (on_button7_clicked),
                      NULL);

  return w_nodes_rm;
}

GtkWidget*
create_w_hb_list (void)
{
  GtkWidget *w_hb_list;
  GtkWidget *vbox6;
  GtkWidget *scrolledwindow5;
  GtkWidget *clist3;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *button8;

  w_hb_list = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_hb_list), "w_hb_list", w_hb_list);
  gtk_widget_set_usize (w_hb_list, 450, 108);
  gtk_window_set_title (GTK_WINDOW (w_hb_list), _("Heatbeat list"));
  gtk_window_set_policy (GTK_WINDOW (w_hb_list), FALSE, TRUE, TRUE);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_list), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (w_hb_list), vbox6);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow5);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_list), "scrolledwindow5", scrolledwindow5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox6), scrolledwindow5, TRUE, TRUE, 0);

  clist3 = gtk_clist_new (5);
  gtk_widget_ref (clist3);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_list), "clist3", clist3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), clist3);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 4, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist3));

  label10 = gtk_label_new (_("Node"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_list), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 0, label10);

  label11 = gtk_label_new (_("Type"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_list), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 1, label11);

  label12 = gtk_label_new (_("Interface"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_list), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 2, label12);

  label13 = gtk_label_new (_("Address"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_list), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 3, label13);

  label14 = gtk_label_new (_("Timeout"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_list), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 4, label14);

  button8 = gtk_button_new_with_label (_("CLOSE"));
  gtk_widget_ref (button8);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_list), "button8", button8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button8);
  gtk_box_pack_start (GTK_BOX (vbox6), button8, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button8, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button8), "clicked",
                      GTK_SIGNAL_FUNC (on_button8_clicked),
                      NULL);

  return w_hb_list;
}

GtkWidget*
create_w_hb_add (void)
{
  GtkWidget *w_hb_add;
  GtkWidget *vbox7;
  GtkWidget *table1;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *combo2;
  GtkWidget *combo_entry2;
  GtkWidget *entry2;
  GtkWidget *hbox4;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *hbuttonbox5;
  GtkWidget *button9;
  GtkWidget *button10;

  w_hb_add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_hb_add), "w_hb_add", w_hb_add);
  gtk_window_set_title (GTK_WINDOW (w_hb_add), _("Add Heartbeat"));

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (w_hb_add), vbox7);

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox7), table1, TRUE, TRUE, 0);

  label15 = gtk_label_new (_("Node:"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table1), label15, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label15), 3, 0);

  label16 = gtk_label_new (_("Device:"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table1), label16, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label16), 3, 0);

  label17 = gtk_label_new (_("Address:"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table1), label17, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label17), 3, 0);

  label18 = gtk_label_new (_("Port:"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table1), label18, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label18), 3, 0);

  label19 = gtk_label_new (_("Timeout:"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table1), label19, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label19), 3, 0);

  combo2 = gtk_combo_new ();
  gtk_widget_ref (combo2);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "combo2", combo2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo2);
  gtk_table_attach (GTK_TABLE (table1), combo2, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry2 = GTK_COMBO (combo2)->entry;
  gtk_widget_ref (combo_entry2);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "combo_entry2", combo_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry2);

  entry2 = gtk_entry_new ();
  gtk_widget_ref (entry2);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "entry2", entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table1), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_table_attach (GTK_TABLE (table1), hbox4, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  spinbutton2_adj = gtk_adjustment_new (224, 224, 240, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_ref (spinbutton2);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "spinbutton2", spinbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton2);
  gtk_box_pack_start (GTK_BOX (hbox4), spinbutton2, TRUE, TRUE, 0);

  spinbutton3_adj = gtk_adjustment_new (0, 0, 254, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_ref (spinbutton3);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "spinbutton3", spinbutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton3);
  gtk_box_pack_start (GTK_BOX (hbox4), spinbutton3, TRUE, TRUE, 0);

  spinbutton4_adj = gtk_adjustment_new (0, 0, 254, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_ref (spinbutton4);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "spinbutton4", spinbutton4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton4);
  gtk_box_pack_start (GTK_BOX (hbox4), spinbutton4, TRUE, TRUE, 0);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 255, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_ref (spinbutton5);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "spinbutton5", spinbutton5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton5);
  gtk_box_pack_start (GTK_BOX (hbox4), spinbutton5, TRUE, TRUE, 0);

  spinbutton6_adj = gtk_adjustment_new (1024, 1024, 65535, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_ref (spinbutton6);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "spinbutton6", spinbutton6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton6);
  gtk_table_attach (GTK_TABLE (table1), spinbutton6, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton7_adj = gtk_adjustment_new (10, 1, 120, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_ref (spinbutton7);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "spinbutton7", spinbutton7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton7);
  gtk_table_attach (GTK_TABLE (table1), spinbutton7, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox5);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "hbuttonbox5", hbuttonbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (vbox7), hbuttonbox5, FALSE, FALSE, 0);

  button9 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button9);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  button10 = gtk_button_new_with_label (_("CANCEL"));
  gtk_widget_ref (button10);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_add), "button10", button10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button10);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button10);
  GTK_WIDGET_SET_FLAGS (button10, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button9), "clicked",
                      GTK_SIGNAL_FUNC (on_button9_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button10), "clicked",
                      GTK_SIGNAL_FUNC (on_button10_clicked),
                      NULL);

  return w_hb_add;
}

GtkWidget*
create_w_hb_disk_add (void)
{
  GtkWidget *w_hb_disk_add;
  GtkWidget *vbox8;
  GtkWidget *table2;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *combo3;
  GtkWidget *combo_entry3;
  GtkWidget *entry3;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *hbuttonbox6;
  GtkWidget *button11;
  GtkWidget *button12;

  w_hb_disk_add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_hb_disk_add), "w_hb_disk_add", w_hb_disk_add);
  gtk_window_set_title (GTK_WINDOW (w_hb_disk_add), _("Add Disk Heartbeat"));

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (w_hb_disk_add), vbox8);

  table2 = gtk_table_new (4, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox8), table2, TRUE, TRUE, 0);

  label22 = gtk_label_new (_("Node:"));
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table2), label22, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label22), 3, 3);

  label23 = gtk_label_new (_("Device:"));
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table2), label23, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label23), 3, 3);

  label24 = gtk_label_new (_("Address:"));
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table2), label24, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label24), 3, 3);

  label25 = gtk_label_new (_("Timeout:"));
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table2), label25, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label25), 3, 3);

  combo3 = gtk_combo_new ();
  gtk_widget_ref (combo3);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "combo3", combo3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo3);
  gtk_table_attach (GTK_TABLE (table2), combo3, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry3 = GTK_COMBO (combo3)->entry;
  gtk_widget_ref (combo_entry3);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "combo_entry3", combo_entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry3);

  entry3 = gtk_entry_new ();
  gtk_widget_ref (entry3);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "entry3", entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry3);
  gtk_table_attach (GTK_TABLE (table2), entry3, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton8_adj = gtk_adjustment_new (0, 0, 16, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_ref (spinbutton8);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "spinbutton8", spinbutton8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton8);
  gtk_table_attach (GTK_TABLE (table2), spinbutton8, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton9_adj = gtk_adjustment_new (10, 1, 120, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_ref (spinbutton9);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "spinbutton9", spinbutton9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spinbutton9);
  gtk_table_attach (GTK_TABLE (table2), spinbutton9, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbuttonbox6 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox6);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "hbuttonbox6", hbuttonbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox6);
  gtk_box_pack_start (GTK_BOX (vbox8), hbuttonbox6, TRUE, TRUE, 0);

  button11 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button11);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "button11", button11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button11);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), button11);
  GTK_WIDGET_SET_FLAGS (button11, GTK_CAN_DEFAULT);

  button12 = gtk_button_new_with_label (_("CANCEL"));
  gtk_widget_ref (button12);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_disk_add), "button12", button12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button12);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), button12);
  GTK_WIDGET_SET_FLAGS (button12, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button11), "clicked",
                      GTK_SIGNAL_FUNC (on_button11_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button12), "clicked",
                      GTK_SIGNAL_FUNC (on_button12_clicked),
                      NULL);

  return w_hb_disk_add;
}

GtkWidget*
create_w_hb_rm (void)
{
  GtkWidget *w_hb_rm;
  GtkWidget *vbox9;
  GtkWidget *hbox5;
  GtkWidget *label26;
  GtkWidget *combo4;
  GtkWidget *combo_entry4;
  GtkWidget *hbuttonbox7;
  GtkWidget *button13;
  GtkWidget *button14;

  w_hb_rm = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_hb_rm), "w_hb_rm", w_hb_rm);
  gtk_window_set_title (GTK_WINDOW (w_hb_rm), _("Remove Heartbeat"));

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_rm), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (w_hb_rm), vbox9);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_rm), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox5, TRUE, TRUE, 0);

  label26 = gtk_label_new (_("HB to remove:"));
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_rm), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox5), label26, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label26), 3, 3);

  combo4 = gtk_combo_new ();
  gtk_widget_ref (combo4);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_rm), "combo4", combo4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo4);
  gtk_box_pack_start (GTK_BOX (hbox5), combo4, TRUE, TRUE, 0);

  combo_entry4 = GTK_COMBO (combo4)->entry;
  gtk_widget_ref (combo_entry4);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_rm), "combo_entry4", combo_entry4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry4);

  hbuttonbox7 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox7);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_rm), "hbuttonbox7", hbuttonbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox7);
  gtk_box_pack_start (GTK_BOX (vbox9), hbuttonbox7, TRUE, TRUE, 0);

  button13 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button13);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_rm), "button13", button13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button13);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button13);
  GTK_WIDGET_SET_FLAGS (button13, GTK_CAN_DEFAULT);

  button14 = gtk_button_new_with_label (_("CANCEL"));
  gtk_widget_ref (button14);
  gtk_object_set_data_full (GTK_OBJECT (w_hb_rm), "button14", button14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button14);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), button14);
  GTK_WIDGET_SET_FLAGS (button14, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button13), "clicked",
                      GTK_SIGNAL_FUNC (on_button13_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button14), "clicked",
                      GTK_SIGNAL_FUNC (on_button14_clicked),
                      NULL);

  return w_hb_rm;
}

GtkWidget*
create_w_srv_add (void)
{
  GtkWidget *w_srv_add;
  GtkWidget *vbox10;
  GtkWidget *table3;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *combo5;
  GtkWidget *combo_entry5;
  GtkWidget *combo6;
  GtkWidget *combo_entry6;
  GtkWidget *entry6;
  GtkWidget *hbuttonbox8;
  GtkWidget *button16;
  GtkWidget *button17;

  w_srv_add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_srv_add), "w_srv_add", w_srv_add);
  gtk_window_set_title (GTK_WINDOW (w_srv_add), _("Add Service"));

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox10);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (w_srv_add), vbox10);

  table3 = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox10), table3, TRUE, TRUE, 0);

  label27 = gtk_label_new (_("Service name:"));
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table3), label27, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label27), 3, 3);

  label28 = gtk_label_new (_("Startup script:"));
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table3), label28, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label28), 3, 3);

  label29 = gtk_label_new (_("Primary node:"));
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table3), label29, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label29), 3, 3);

  label30 = gtk_label_new (_("Secondary node:"));
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table3), label30, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label30), 3, 3);

  label31 = gtk_label_new (_("Check-up script:"));
  gtk_widget_ref (label31);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "label31", label31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table3), label31, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label31), 3, 3);

  entry4 = gtk_entry_new_with_max_length (16);
  gtk_widget_ref (entry4);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "entry4", entry4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry4);
  gtk_table_attach (GTK_TABLE (table3), entry4, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry5 = gtk_entry_new_with_max_length (256);
  gtk_widget_ref (entry5);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "entry5", entry5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry5);
  gtk_table_attach (GTK_TABLE (table3), entry5, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo5 = gtk_combo_new ();
  gtk_widget_ref (combo5);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "combo5", combo5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo5);
  gtk_table_attach (GTK_TABLE (table3), combo5, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry5 = GTK_COMBO (combo5)->entry;
  gtk_widget_ref (combo_entry5);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "combo_entry5", combo_entry5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry5);

  combo6 = gtk_combo_new ();
  gtk_widget_ref (combo6);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "combo6", combo6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo6);
  gtk_table_attach (GTK_TABLE (table3), combo6, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  combo_entry6 = GTK_COMBO (combo6)->entry;
  gtk_widget_ref (combo_entry6);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "combo_entry6", combo_entry6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry6);

  entry6 = gtk_entry_new_with_max_length (256);
  gtk_widget_ref (entry6);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "entry6", entry6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry6);
  gtk_table_attach (GTK_TABLE (table3), entry6, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbuttonbox8 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox8);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "hbuttonbox8", hbuttonbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox8);
  gtk_box_pack_start (GTK_BOX (vbox10), hbuttonbox8, TRUE, TRUE, 0);

  button16 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button16);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "button16", button16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button16);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), button16);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  button17 = gtk_button_new_with_label (_("CANCEL"));
  gtk_widget_ref (button17);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_add), "button17", button17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button17);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button16), "clicked",
                      GTK_SIGNAL_FUNC (on_button16_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button17), "clicked",
                      GTK_SIGNAL_FUNC (on_button17_clicked),
                      NULL);

  return w_srv_add;
}

GtkWidget*
create_w_srv_rm (void)
{
  GtkWidget *w_srv_rm;
  GtkWidget *vbox11;
  GtkWidget *hbox6;
  GtkWidget *label32;
  GtkWidget *combo7;
  GtkWidget *combo_entry7;
  GtkWidget *hbuttonbox9;
  GtkWidget *button18;
  GtkWidget *button19;

  w_srv_rm = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_srv_rm), "w_srv_rm", w_srv_rm);
  gtk_window_set_title (GTK_WINDOW (w_srv_rm), _("Remove Service"));

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox11);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_rm), "vbox11", vbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (w_srv_rm), vbox11);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_rm), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox6, TRUE, TRUE, 0);

  label32 = gtk_label_new (_("Service:"));
  gtk_widget_ref (label32);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_rm), "label32", label32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox6), label32, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label32), 3, 3);

  combo7 = gtk_combo_new ();
  gtk_widget_ref (combo7);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_rm), "combo7", combo7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo7);
  gtk_box_pack_start (GTK_BOX (hbox6), combo7, TRUE, TRUE, 0);

  combo_entry7 = GTK_COMBO (combo7)->entry;
  gtk_widget_ref (combo_entry7);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_rm), "combo_entry7", combo_entry7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry7);

  hbuttonbox9 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox9);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_rm), "hbuttonbox9", hbuttonbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox9);
  gtk_box_pack_start (GTK_BOX (vbox11), hbuttonbox9, TRUE, TRUE, 0);

  button18 = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (button18);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_rm), "button18", button18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button18);
  gtk_container_add (GTK_CONTAINER (hbuttonbox9), button18);
  GTK_WIDGET_SET_FLAGS (button18, GTK_CAN_DEFAULT);

  button19 = gtk_button_new_with_label (_("CANCEL"));
  gtk_widget_ref (button19);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_rm), "button19", button19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button19);
  gtk_container_add (GTK_CONTAINER (hbuttonbox9), button19);
  GTK_WIDGET_SET_FLAGS (button19, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button18), "clicked",
                      GTK_SIGNAL_FUNC (on_button18_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button19), "clicked",
                      GTK_SIGNAL_FUNC (on_button19_clicked),
                      NULL);

  return w_srv_rm;
}

GtkWidget*
create_w_srv_list (void)
{
  GtkWidget *w_srv_list;
  GtkWidget *vbox12;
  GtkWidget *scrolledwindow6;
  GtkWidget *clist4;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *hbuttonbox10;
  GtkWidget *button20;

  w_srv_list = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (w_srv_list), "w_srv_list", w_srv_list);
  gtk_window_set_title (GTK_WINDOW (w_srv_list), _("Service list"));

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox12);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "vbox12", vbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (w_srv_list), vbox12);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow6);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "scrolledwindow6", scrolledwindow6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow6);
  gtk_box_pack_start (GTK_BOX (vbox12), scrolledwindow6, TRUE, TRUE, 0);

  clist4 = gtk_clist_new (5);
  gtk_widget_ref (clist4);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "clist4", clist4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist4);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), clist4);
  gtk_widget_set_usize (clist4, 515, 26);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 1, 101);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 2, 101);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 3, 97);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 4, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist4));

  label33 = gtk_label_new (_("Name"));
  gtk_widget_ref (label33);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "label33", label33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label33);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 0, label33);

  label34 = gtk_label_new (_("Startup script"));
  gtk_widget_ref (label34);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "label34", label34,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label34);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 1, label34);

  label35 = gtk_label_new (_("Primary node"));
  gtk_widget_ref (label35);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "label35", label35,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label35);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 2, label35);
  gtk_widget_set_usize (label35, 82, 15);

  label36 = gtk_label_new (_("Secondary node"));
  gtk_widget_ref (label36);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "label36", label36,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label36);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 3, label36);
  gtk_widget_set_usize (label36, 82, 15);

  label37 = gtk_label_new (_("Check-up script"));
  gtk_widget_ref (label37);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "label37", label37,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label37);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 4, label37);

  hbuttonbox10 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox10);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "hbuttonbox10", hbuttonbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox10);
  gtk_box_pack_start (GTK_BOX (vbox12), hbuttonbox10, TRUE, TRUE, 0);

  button20 = gtk_button_new_with_label (_("CLOSE"));
  gtk_widget_ref (button20);
  gtk_object_set_data_full (GTK_OBJECT (w_srv_list), "button20", button20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button20);
  gtk_container_add (GTK_CONTAINER (hbuttonbox10), button20);
  GTK_WIDGET_SET_FLAGS (button20, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button20), "clicked",
                      GTK_SIGNAL_FUNC (on_button20_clicked),
                      NULL);

  return w_srv_list;
}

