/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_w_main (void);
GtkWidget* create_w_preferences (void);
GtkWidget* create_w_nodes_list (void);
GtkWidget* create_w_nodes_add (void);
GtkWidget* create_w_nodes_rm (void);
GtkWidget* create_w_hb_list (void);
GtkWidget* create_w_hb_add (void);
GtkWidget* create_w_hb_disk_add (void);
GtkWidget* create_w_hb_rm (void);
GtkWidget* create_w_srv_add (void);
GtkWidget* create_w_srv_rm (void);
GtkWidget* create_w_srv_list (void);
