/*
-----------------------------------------------------------------------------
Filename:    CVisualX.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.8.x Application Wizard for VC10 (May 2012)
      https://bitbucket.org/jacmoe/ogreappwizards
-----------------------------------------------------------------------------
*/
#ifndef __CVisualX_h_
#define __CVisualX_h_

#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../res/resource.h"
#endif

#include "Sky.h"
#include "Ocean.h"
#include "Terrain.h"
#include "Target.h"
#include "InputController.h"


class CVisualX : public BaseApplication
{
public:
    CVisualX(void);
    virtual ~CVisualX(void);

protected:
    virtual void createScene(void);
	void setupResources(void);

	virtual bool frameStarted( const FrameEvent &evt );
    virtual void createFrameListener(void);

    virtual bool keyPressed(const OIS::KeyEvent &arg);
    virtual bool keyReleased(const OIS::KeyEvent &arg);

	/**
	* @function		CheckCollision
	* @return		true if camera is about to collide with any target
	*/
	bool CheckCollision(const Ogre::Vector3& position, const Ogre::Vector3& direction);

protected:
	CSky*		m_pSky;
	COcean*		m_pOcean;
	CTerrain*	m_pTerrain;
	CInputController*	m_pInputController;

	std::list<CTarget*>	m_listTarget;

	Ogre::RaySceneQuery *mRaySceneQuery;
	MOC::CollisionTools*		m_pCollisionTools;
	bool		m_bCollision;

};

#endif // #ifndef __CVisualX_h_
