/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ProbedObject */

#ifndef _Included_ProbedObject
#define _Included_ProbedObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ProbedObject
 * Method:    objectCreateStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ProbedObject_objectCreateStart
  (JNIEnv *, jobject);

/*
 * Class:     ProbedObject
 * Method:    objectCreateEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ProbedObject_objectCreateEnd
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
