//////////////////////////////////////////////////////////////////////////
//
// DDS MESSAGE, TDSR-MMI
//
// Created	: 2012.06.10  : Lee-SooJung
// Updated	: 
//
//////////////////////////////////////////////////////////////////////////


//------------------------------------------------------------------------
//	TDSR MMI -> CMS
//------------------------------------------------------------------------
//	1. DMSG_TDSR_FIELDSETRESULT			영역설정결과
//	2. DMSG_TDSR_JAMMING				방해전파원정보
//	3. DMSG_TDSR_STATE					상태정보
//	4. DMSG_TDSR_TARGET					표적정보
//	5. DMSG_TDSR_BSCOPE					B-SCOPE 데이터
//  6. DMSG_TDSR_TWSTRACKING			TWS 추적정보
//  7. DMSG_TDSR_COLUMNOFWATER			물기둥 정보
//------------------------------------------------------------------------


//	1. 영역설정결과
struct DMSG_TDSR_FIELDSETRESULT
{
	char		byFieldCategory;				// 영역 종류, 1: 대함 AIA, 2: 대함 AIIA, 3: Blank Sector, 4: AONI
	char		byFieldConfig;					// 영역 설정, 1: 추가, 2: 수정, 3: 삭제
	char		bySerialNumber;					// 일련 번호, AIA : 1-4, AIIA : 1-2, Blank Sector: 1-2,
	double		dStartBearing;					// 시작방위
	double		dEndBearing;					// 종료방위
	double		dStartDistance;					// 시작거리
	double		dEndDistance;					// 종료거리
	double		dStartAltitude;					// 시작고각
	double		dEndAltitude;					// 종료고각
	char		byStandardPoint;				// 기준점, 1: 자함중심, 2: 지도중심
};


//  2. 방해전파원정보
struct DMSG_TDSR_JAMMING
{
	double		dTime;							// 시간
	char		ReceiveRFChannel;				// 수신RF 채널
	double		dBearing;						// 방위각
	double		dAltitude;						// 고각
};


//  3. 상태정보
struct DMSG_TDSR_STATE
{
	char		StateInfo;						// 상태정보, 1: 운영, 2: 비운영
	char		ValidState;						// 유효상태, 1: 유효, 2: 비유효
	char		BattleShort;					// 1: On, 2: Off
	char		PlatformControl;				// 플랫폼 제어상태, 1: Standby, 2: Test, 3: StartUp, 4: On, 5: On Zero, 6: Fail, 7: Man Aloft
	char		BDriveControl;					//  1: Standby, 2: Stopped at Required Bearing, 3: Test, 4: StartUp, 5: On, 6: Fail, 7: Man Aloft
	long		BDriveAngle;					// B 드라이브 각도
	char		TransmitterControl;				// 송신기 제어 상태, 1: Init, 2: Standby, 3: Warm up, 4: Ready, 5: Transmit, 6: Fail
	char		DuctingMode;					// 1: On, 2: Off
	char		RadarSlience;					// 1: On, 2: Off
	char		RFChannel1State;				// 1: On, 2: Off	
	char		RFChannel2State;				// 1: On, 2: Off	
	char		RFChannel3State;				// 1: On, 2: Off	
	char		RFChannel4State;				// 1: On, 2: Off	
	char		RFChannel5State;				// 1: On, 2: Off	
	char		RFChannel6State;				// 1: On, 2: Off	
	char		RFChannel7State;				// 1: On, 2: Off	
	char		RFChannel8State;				// 1: On, 2: Off	
	char		RFMode;							// RF 모드 상태, 1: RF Fixed 1Mode, 2: RF Fixed 2 Mode, 3: RF Stagger 1Mode, 4: RF Stagger 2 Mode
	char		VideoMode;						// 비디오 모드, 1: Burst Video, 2: Normal Video, 3: Duct Video
	char		VideoFilter;					// 비디오 필터, 1: Raw, 2: Filtered
	char		VideoSTCType;					// 비디오 STC 타입, 1: STC1, 2: STC2. 3: STC3, 4: STC4
	char		VideoThreshold;					// 비디오 쓰레쉬 홀드, 1: Fixed, 2: Manual

};


//	4. 표적정보
struct DMSG_TDSR_TARGET
{
	long			nTarget_Number;				//표적 번호
	double			dSystem_Time;				//시간
	char			Target_Category;			//표적 분류, 1:대공, 2:대함
	double			dPosX;						// 위치
	double			dPosY;
	double			dPosZ;						// 대공인 경우만 유효
	double			dVelocityX;					// 속력
	double			dVelocityY;
	double			dVelocityZ;					// 대공인 경우만 유효	
	double			dRange_Accuracy;			//Distance
	double			dBearing_Accuracy;
	double			dElevation_Accuracy;		//대공표적인 경우 유효
	char			Track_Phase;				//1:Tracking, 2:Lost by Sensor, 3: Deleted by Sensor
};



//  5. B-SCOPE 데이터
struct DMSG_TDSR_BSCOPE
{
	long nTWS_ID;
	char cGreen[40000];
};



//  6. 물기둥 정보
struct DMSG_TDSR_COLUMNOFWATER 
{
	long		nTWS_ID;
	long		nID;
	double		dDegree;
	double		dRange;
};




//  7. TWS 추적정보
struct DMSG_TDSR_TWSTRACKING 
{
	long		nTWS_TrackingInfo;			// TWS 추적정보
	long		nTarget_Number;				//표적 번호
	double		dSystem_Time;				//시간
	char		cTarget_Category;			//표적 분류, 1:대공, 2:대함
	double		dPosX;						// 위치
	double		dPosY;
	double		dPosZ;						// 대공인 경우만 유효
	double		dVelocityX;					// 속력
	double		dVelocityY;
	double		dVelocityZ;					// 대공인 경우만 유효
	double		dRange_Accuracy;			//Distance
	double		dBearing_Accuracy;
	double		dElevation_Accuracy;		//대공표적인 경우 유효
	char		cTrack_Phase;				//1:Tracking, 2:Lost by Sensor, 3: Deleted by Sensor
};





//------------------------------------------------------------------------
//	CMS -> TDSR MMI
//------------------------------------------------------------------------
//	1.  DMSG_HMI_TDSRANTENNACTRL				안테나 통제
//	2.  DMSG_HMI_TDSRBATTLESHORTCMD				비상운용모드
//	3.  DMSG_HMI_TDSRTRANSMITTERCTRL			송신기 통제
//	4.  DMSG_OSM_TDSRFIELDSET					영역 설정
//	5.  DMSG_HMI_TDSRSURFACETRACKCTRL			SurfaceTrack 설정
//	6.  DMSG_HMI_TDSRRDRSILENCECTRL				방사통제
//	7.  DMSG_HMI_TDSRSENDCHANNELSET				송신주파수 설정
//	8.  DMSG_HMI_TDSRSENDRFMODE					Transmitter RF 모드
//  9.  DMSG_HMI_TDSRBLANKSECTORCTRL			블랭크섹터
//	10. DMSG_HMI_TDSRVIDEOSET					비디오 설정
//	11. DMSG_HMI_TDSRVIDEOREQ					영상 요청
//	12. DMSG_HMI_TDSRRDRMODESET					레이더모드 설정
//	13. DMSG_HMI_TDSRAIRTRACKINGSET				대공추적모드 설정
//	14. DMSG_HMI_TDSRSHIPTRACKINGSET			대함추적모드 설정
//	15. DMSG_HMI_TDSRJAMMINGDETECTSET			방해전파 탐지설정
//	16. DMSG_HMI_TDSRLOWSPEEDDETECTSET			저속탐지설정
//	17. DMSG_HMI_TDSRLOWALTDETECTSET			저고도탐지설정
//	18. DMSG_HMI_TDSRSIDELOBEBLOCK				부엽차단설정
//	19. DMSG_HMI_TDSREQUIPQUITSET				장비종료설정
//	20. DMSG_EC_TDSRTWSTARGETDESIG				TWS표적지정
//------------------------------------------------------------------------


//	1. 안테나 통제
struct DMSG_HMI_TDSRANTENNACTRL
{
	char	PlatformControl;					// 1: Standby, 2: Run
	char	BDriveControl;						// 1: Stop At Required Bearing, 2: Run
	long	nRequiredBearing;
};


//	2. 비상운용모드
struct DMSG_HMI_TDSRBATTLESHORTCMD
{
	char	BattleShot;							// 1: Start, 2: Stop
};


//	3. 송신기 통제
struct DMSG_HMI_TDSRTRANSMITTERCTRL
{
	char	TransmitterControl;					//1: Stanby, 2: Ready, 3: Transmit, 4: Soft reset
};


//	4. 영역 설정
struct DMSG_OSM_TDSRFIELDSET
{
	char			SiteCategory;					// 1: 대함 AIA, 2: 대함 AIIA, 3: Black Sector, 4: AONI
	unsigned long	nID;
	char			OnOff;							// 1: 추가, 2: 수정, 3: 삭제
	char			SerialNumber;					// AIA : TBD, AIIA :TBD, Blank Sector: TBD, AONI : TBD
	double			dStartBearing;					// 시작방위
	double			dEndBearing;					// 종료방위
	double			dStartDistance;					// 시작거리
	double			dEndDistance;					// 종료거리
	double			dStartAltitude;					// 시작고각
	double			dEndAltitude;					// 종료고각
	char			StandardPoint;					// 기준점, 1: 자함중심, 2: 지도중심
};


//	5. SurfaceTrack 설정
struct DMSG_HMI_TDSRSURFACETRACKCTRL
{
	char		command;						// 1: Init, 2: Update, 3: Cancel
	long		nTrackNum;
	double		dPosX;
	double		dPosY;
	double		dTimeValidity;
};


//	6. 방사통제
struct DMSG_HMI_TDSRRDRSILENCECTRL
{
	char		cCommand;						// 1: Init, 2: Update, 3: Cancel
};


//	7. 송신주파수 설정
struct DMSG_HMI_TDSRSENDCHANNELSET
{
	char			FreqVariableSys;				// 주파수 가변방식, 1: 고정, 2: 가변
	char			ReceiveChannel;					// 송신채널, 1~10 // 고정인 경우엔 유효
	unsigned short	usSetRFChannel;				// 허용 RF채널 설정	각 비트 연산을 한다.밑의 각 값과 & 연산하여 True이면 ON, False이면 OFF
												// RF채널은 여러 개 설정 가능
												// 0x0001 : RF채널 1  0x0002 : RF채널 2   0x0004 : RF채널 3  0x0008 : RF채널 4
												// 0x0010 : RF채널 5  0x0020 : RF채널 6   0x0040 : RF채널 7  0x0080 : RF채널 8
												// 0x0100 : RF채널 9  0x0200 : RF채널 10		
};


//	8. Transmitter RF 모드
struct DMSG_HMI_TDSRSENDRFMODE
{
	char		RFMode;							// 1: Fix1, 2: Fix2, 3: Stagger1, 4: Stagger2
};


//  9. 블랭크섹터
struct DMSG_HMI_TDSRBLANKSECTORCTRL
{
	char		cBlanckSector;
};




//	10. 비디오 설정
struct DMSG_HMI_TDSRVIDEOSET
{
	char		VideoMode;						// 비디오 모드, 1: 정상, 2: 버스트, 3: 덕트
	char		StcCurve;						// 1: STC1, 2: STC2, 3: STC3, 4: STC4
	char		VideoClutterFilter;				// 1: Raw, 2: Filtered
	char		VideoLimitMode;					// 비디오 임계치 모드, 1: 고정, 2: 수동
	long		nVideoLimitValue;				// 비디오 임계치, 비디오 임계치가 수동인 경우
	char		DuctingConfigMode;				// 덕팅처리 설정, 비디오모드가 덕트인 경우에만!!! 1: 작동, 2: 중지

};


//	11. 영상 요청
struct DMSG_HMI_TDSRVIDEOREQ				
{
	char	VideoRequestStatus;					// 1: 영상요청, 2: 영상중지
};	


//	12. 레이더모드 설정
struct DMSG_HMI_TDSRRDRMODESET		
{
	char	ManagementMode;						// 1: 탐색, 2: 자기방어
	char	PRF;								// 1: 고정, 2: 가변 
};


//	13. 대공추적모드 설정
struct DMSG_HMI_TDSRAIRTRACKINGSET		
{
	char	Mode;								// 1: 최적, 2: 최대
};


//	14. 대함추적모드 설정
struct DMSG_HMI_TDSRSHIPTRACKINGSET		 
{
	char	Mode;								// 1: 최적, 2: 최대
};


//	15. 방해전파 탐지설정
struct DMSG_HMI_TDSRJAMMINGDETECTSET	
{
	char	DetectMode;							// 1: 작동, 2: 중지
};


//	16. 저속탐지설정
struct DMSG_HMI_TDSRLOWSPEEDDETECTSET	
{
	char	LowDetectConfig;					// 1: 단계1, 2: 단계2, 3: 단계3, 4: 중지
};


//	17. 저고도탐지설정
struct DMSG_HMI_TDSRLOWALTDETECTSET
{
	char	LowAltitudeConfig;					// 1: 작동, 2: 중지
};


//	18. 부엽차단설정
struct DMSG_HMI_TDSRSIDELOBEBLOCK			
{
	char SubLobeBlock;							// 1: 작동, 2: 중지

};


//	19. 장비종료설정
struct DMSG_HMI_TDSREQUIPQUITSET		
{
	char	EquitQuitConfig;					// 1: 장비 끔
};


//	20. TWS표적지정
struct DMSG_EC_TDSRTWSTARGETDESIG			
{
	char		byTrackingStatus;				// 0: Start Tracking, 1: Stop Tracking
	char		TrackingChannel;				// 추적채널 , 1: TWS-1, 2: TWS-2
	long		nTargetNumber;
	double		dPosX;							// 위치
	double		dPosY;
	double		dPosZ;
};