/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeSelect */

#ifndef _Included_NativeSelect
#define _Included_NativeSelect
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: port */
/*
 * Class:     NativeSelect
 * Method:    native_close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_NativeSelect_native_1close
  (JNIEnv *, jclass, jint);

/*
 * Class:     NativeSelect
 * Method:    native_get_request
 * Signature: ()LNativeRequest;
 */
JNIEXPORT jobject JNICALL Java_NativeSelect_native_1get_1request
  (JNIEnv *, jclass);

/*
 * Class:     NativeSelect
 * Method:    native_initialize_port
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeSelect_native_1initialize_1port
  (JNIEnv *, jclass, jint);

/*
 * Class:     NativeSelect
 * Method:    native_set_stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_NativeSelect_native_1set_1stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     NativeSelect
 * Method:    native_write
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_NativeSelect_native_1write
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
