/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: MAX_FILE_SIZE */
/* Inaccessible static: PAGE_SIZE */
/* Inaccessible static: MAX_PAGES */
/* Inaccessible static: MAX_THREADS */
/* Inaccessible static: MAX_DENSITY */
/* Inaccessible static: MAX_READS */
/* Inaccessible static: hits */
/* Inaccessible static: density */
/* Inaccessible static: path */
/* Inaccessible static: spinTime */
/* Inaccessible static: runtime */
/* Inaccessible static: nThreads */
/* Inaccessible static: iterations */
/* Inaccessible static: setConcurrency */
/* Inaccessible static: nProcessed */
/* Inaccessible static: DEBUG */
/* Inaccessible static: threads */
/* Inaccessible static: stop */
/*
 * Class:     Test
 * Method:    pthread_setconcurrency
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Test_pthread_1setconcurrency
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
