/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class Test */
/* SYMBOL: "Test/pthread_setconcurrency(I)V", Java_Test_pthread_0005fsetconcurrency_stub */
stack_item *Java_Test_pthread_0005fsetconcurrency_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void Test_pthread_setconcurrency(void *,int32_t);
	(void) Test_pthread_setconcurrency(NULL,((_P_[0].i)));
	return _P_;
}
